### ISSUE TITLE
how to get the nee2021.nc?

### ISSUE THREAD

**Issue by ArchimedesWithoutme** [cxiao13/carbon-sink-hemisphere#1]

**Comment by ArchimedesWithoutme** [comment]
Dear chen, I noticed there's no original data in your data folder

**Comment by cxiao13** [comment]
Hi, thanks for pointing this out. Unfortunately, you have to submit a request for the data through https://globalcarbonbudgetdata.org/closed-access-requests.html.

**Comment by cxiao13** [comment]
Resolved by providing the data acquirement link.
